// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistema_vacaciones.Models;

#nullable disable

namespace sistema_vacaciones.Migrations
{
    [DbContext(typeof(SistemaVacacionesContext))]
    [Migration("20241211073057_funcionarios-tabla")]
    partial class funcionariostabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sistema_vacaciones.Models.Departamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("sistema_vacaciones.Models.Funcionarios", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEmpleadoId")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("TipoEmpleadoId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("sistema_vacaciones.Models.TipoEmpleados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("NumeroDias")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TipoEmpleados");
                });

            modelBuilder.Entity("sistema_vacaciones.Models.Funcionarios", b =>
                {
                    b.HasOne("sistema_vacaciones.Models.Departamentos", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_vacaciones.Models.TipoEmpleados", "TipoEmpleado")
                        .WithMany("Funcionarios")
                        .HasForeignKey("TipoEmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("TipoEmpleado");
                });

            modelBuilder.Entity("sistema_vacaciones.Models.Departamentos", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("sistema_vacaciones.Models.TipoEmpleados", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
